
path: C:/Users/aaron/Documents/Coding/Calorie-Counter/data  # dataset root dir
train: images/train  # train images (relative to 'path')
val: images/valid  # val images (relative to 'path')

# Classes
names:
  0: banana
  1: cheesecake
  2: strawberry
  3: sphagetti
  4: pancake
  5: screen
  6: donut
  7: pho
  8: pizza
  9: scallop
  10: taco