
path: C:/Users/aaron/Documents/Coding/Calorie-Counter  # dataset root dir
train: data/images  # train images (relative to 'path')
val: data/images  # val images (relative to 'path')

# Classes
names:
  0: banana
  1: cheesecake
  2: strawberry
  3: sphagetti
  4: pancake
  5: credit_card
  6: donut
  7: pho
  8: pizza
  9: scallop
  10: taco